DROP TABLE IF EXISTS raw_mental_health_burnout_tech_2026;

CREATE TABLE raw_mental_health_burnout_tech_2026 (
    employee_id INTEGER,
    age INTEGER,
    gender TEXT,
    country TEXT,
    job_role TEXT,
    seniority_level TEXT,
    years_experience INTEGER,
    years_at_company DOUBLE PRECISION,
    company_size TEXT,
    industry TEXT,
    work_mode TEXT,
    salary_usd INTEGER,
    work_hours_per_week INTEGER,
    meetings_per_day DOUBLE PRECISION,
    team_size INTEGER,
    sleep_hours_per_night DOUBLE PRECISION,
    exercise_days_per_week INTEGER,
    vacation_days_taken INTEGER,
    therapy_access INTEGER,
    uses_therapy INTEGER,
    ai_tools_daily INTEGER,
    manager_support_score DOUBLE PRECISION,
    work_life_balance_score DOUBLE PRECISION,
    job_satisfaction_score DOUBLE PRECISION,
    social_support_score DOUBLE PRECISION,
    deadline_pressure_score DOUBLE PRECISION,
    autonomy_score DOUBLE PRECISION,
    stress_score DOUBLE PRECISION,
    burnout_score DOUBLE PRECISION,
    phq9_score INTEGER,
    phq9_category TEXT,
    gad7_score INTEGER,
    gad7_category TEXT,
    burnout_level TEXT,
    seeks_mental_health_support INTEGER,
    job_change_intention INTEGER
);
