# Generated by Django 5.2.15 on 2026-06-10 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGQueryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(db_index=True, unique=True)),
                ('question', models.CharField(max_length=4000)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro')], db_index=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('top_k', models.PositiveSmallIntegerField()),
                ('source_count', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField()),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='rag_ragquer_status_0ec91f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RAGQuerySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(db_index=True, max_length=64)),
                ('source_name', models.CharField(db_index=True, max_length=500)),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.FloatField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_sources', to='rag.ragqueryrecord')),
            ],
            options={
                'ordering': ['query_id', 'rank'],
                'indexes': [models.Index(fields=['document_id', 'source_name'], name='rag_ragquer_documen_e20fee_idx')],
                'constraints': [models.UniqueConstraint(fields=('query', 'rank'), name='unique_query_source_rank')],
            },
        ),
    ]
