"""Generate an interactive visual dashboard for the project.

The script consumes the statistical outputs already generated by
`scripts/statistical_analysis.py` and queries PostgreSQL for chart-level data.
It exports HTML charts, supporting CSV files and an index dashboard page to
`outputs/dashboard`.

Usage:
    python scripts/dashboard_visual.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from db import env, read_sql, wait_for_database
from statistical_analysis import main as generate_statistics


PROJECT_ROOT = Path(__file__).resolve().parents[1]
STATISTICS_DIR = PROJECT_ROOT / "outputs" / "statistics"
DASHBOARD_DIR = PROJECT_ROOT / "outputs" / "dashboard"
CHARTS_DIR = DASHBOARD_DIR / "charts"
DATA_DIR = DASHBOARD_DIR / "data"
CLEAN_TABLE = env("CLEAN_TABLE", "clean_mental_health_burnout_tech_2026")

COMMON_LAYOUT = {
    "template": "plotly_white",
    "font": {"family": "Arial, sans-serif", "size": 13},
    "margin": {"l": 70, "r": 30, "t": 80, "b": 70},
}

def ensure_statistics_outputs() -> None:
    required_files = [
        "categorical_frequencies.csv",
        "correlation_matrix.csv",
        "grouped_kpis.csv",
        "kpi_summary.json",
    ]
    missing = [name for name in required_files if not (STATISTICS_DIR / name).exists()]
    if not missing:
        return

    print("Saidas estatisticas ausentes. Gerando novamente...")
    generate_statistics()


def prepare_directories() -> None:
    CHARTS_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)


def save_data(df: pd.DataFrame, filename: str) -> None:
    path = DATA_DIR / filename
    df.to_csv(path, index=False, encoding="utf-8")
    print(f"Dataset visual gerado: {path.relative_to(PROJECT_ROOT)}")


def save_chart(fig: go.Figure, filename: str) -> None:
    path = CHARTS_DIR / filename
    fig.update_layout(**COMMON_LAYOUT)
    fig.write_html(path, include_plotlyjs=True, full_html=True)
    print(f"Grafico gerado: {path.relative_to(PROJECT_ROOT)}")


def create_burnout_distribution_chart() -> None:
    frequencies = pd.read_csv(STATISTICS_DIR / "categorical_frequencies.csv")
    burnout = frequencies[frequencies["coluna"] == "burnout_level"].copy()
    order = ["Low", "Moderate", "High", "Severe"]
    burnout["categoria"] = pd.Categorical(burnout["categoria"], categories=order, ordered=True)
    burnout = burnout.sort_values("categoria")
    save_data(burnout, "burnout_level_distribution.csv")

    fig = px.bar(
        burnout,
        x="categoria",
        y="frequencia_absoluta",
        color="categoria",
        text="frequencia_relativa_pct",
        title="Distribuicao dos niveis de burnout",
        labels={
            "categoria": "Nivel de burnout",
            "frequencia_absoluta": "Quantidade de profissionais",
            "frequencia_relativa_pct": "Percentual",
        },
        color_discrete_sequence=["#2f6f73", "#9ab85f", "#d99645", "#c94b4b"],
    )
    fig.update_traces(texttemplate="%{text:.2f}%", textposition="outside")
    fig.update_layout(showlegend=False)
    save_chart(fig, "01_burnout_level_distribution.html")


def create_stress_histogram_chart() -> None:
    sql = f"""
        SELECT stress_score
        FROM {CLEAN_TABLE}
        WHERE stress_score IS NOT NULL;
    """
    stress = read_sql(sql)
    save_data(stress, "stress_score_values.csv")

    fig = px.histogram(
        stress,
        x="stress_score",
        nbins=30,
        title="Distribuicao do score de estresse",
        labels={"stress_score": "Score de estresse", "count": "Quantidade de profissionais"},
        color_discrete_sequence=["#4f7cac"],
    )
    fig.update_layout(yaxis_title="Quantidade de profissionais", bargap=0.04)
    save_chart(fig, "02_stress_score_histogram.html")


def create_burnout_by_work_mode_boxplot() -> None:
    sql = f"""
        SELECT work_mode, burnout_score
        FROM {CLEAN_TABLE}
        WHERE work_mode IS NOT NULL
          AND burnout_score IS NOT NULL;
    """
    data = read_sql(sql)
    save_data(data, "burnout_score_by_work_mode.csv")

    fig = px.box(
        data,
        x="work_mode",
        y="burnout_score",
        color="work_mode",
        title="Burnout por modelo de trabalho",
        labels={"work_mode": "Modelo de trabalho", "burnout_score": "Score de burnout"},
        color_discrete_sequence=["#537a5a", "#b56945", "#596a9a"],
        points=False,
    )
    fig.update_layout(showlegend=False)
    save_chart(fig, "03_burnout_by_work_mode_boxplot.html")


def create_stress_burnout_scatter_chart() -> None:
    sql = f"""
        SELECT
            stress_score,
            burnout_score,
            work_hours_per_week,
            sleep_hours_per_night,
            work_mode
        FROM {CLEAN_TABLE}
        WHERE stress_score IS NOT NULL
          AND burnout_score IS NOT NULL
        ORDER BY random()
        LIMIT 6000;
    """
    data = read_sql(sql)
    save_data(data, "stress_burnout_sample.csv")

    fig = px.scatter(
        data,
        x="stress_score",
        y="burnout_score",
        color="work_mode",
        size="work_hours_per_week",
        hover_data=["sleep_hours_per_night"],
        opacity=0.55,
        title="Relacao entre estresse e burnout",
        labels={
            "stress_score": "Score de estresse",
            "burnout_score": "Score de burnout",
            "work_mode": "Modelo de trabalho",
            "work_hours_per_week": "Horas semanais",
            "sleep_hours_per_night": "Horas de sono",
        },
        color_discrete_sequence=["#537a5a", "#b56945", "#596a9a"],
    )
    save_chart(fig, "04_stress_vs_burnout_scatter.html")


def create_correlation_heatmap_chart() -> None:
    correlation = pd.read_csv(STATISTICS_DIR / "correlation_matrix.csv")
    correlation = correlation.set_index("variavel")
    save_data(correlation.reset_index(), "correlation_matrix.csv")

    fig = px.imshow(
        correlation,
        text_auto=".2f",
        aspect="auto",
        color_continuous_scale="RdBu_r",
        zmin=-1,
        zmax=1,
        title="Mapa de calor de correlacao",
        labels={"color": "Correlacao"},
    )
    fig.update_xaxes(tickangle=45)
    save_chart(fig, "05_correlation_heatmap.html")


def create_grouped_kpi_chart() -> None:
    grouped = pd.read_csv(STATISTICS_DIR / "grouped_kpis.csv")
    work_mode = grouped[grouped["dimensao"] == "work_mode"].copy()
    save_data(work_mode, "work_mode_kpis.csv")

    fig = go.Figure()
    fig.add_trace(
        go.Bar(
            x=work_mode["categoria"],
            y=work_mode["burnout_score_medio"],
            name="Burnout medio",
            marker_color="#c94b4b",
        )
    )
    fig.add_trace(
        go.Bar(
            x=work_mode["categoria"],
            y=work_mode["stress_score_medio"],
            name="Estresse medio",
            marker_color="#4f7cac",
        )
    )
    fig.update_layout(
        title="Burnout e estresse medio por modelo de trabalho",
        xaxis_title="Modelo de trabalho",
        yaxis_title="Score medio",
        barmode="group",
    )
    save_chart(fig, "06_work_mode_kpis.html")


def read_kpis() -> dict[str, float]:
    with (STATISTICS_DIR / "kpi_summary.json").open(encoding="utf-8") as file:
        return json.load(file)


def create_dashboard_index() -> None:
    kpis = read_kpis()
    chart_files = [
        "01_burnout_level_distribution.html",
        "02_stress_score_histogram.html",
        "03_burnout_by_work_mode_boxplot.html",
        "04_stress_vs_burnout_scatter.html",
        "05_correlation_heatmap.html",
        "06_work_mode_kpis.html",
    ]
    cards = [
        ("Registros", f"{int(kpis['total_registros']):,}".replace(",", ".")),
        ("Burnout severo", f"{kpis['burnout_severe_pct']:.2f}%"),
        ("Burnout alto/severo", f"{kpis['burnout_high_or_severe_pct']:.2f}%"),
        ("Estresse medio", f"{kpis['stress_score_medio']:.2f}"),
        ("Horas semanais", f"{kpis['horas_semanais_media']:.2f}"),
        ("Usa terapia", f"{kpis['usa_terapia_pct']:.2f}%"),
    ]

    cards_html = "\n".join(
        f"""
        <section class="kpi-card">
            <span>{title}</span>
            <strong>{value}</strong>
        </section>
        """
        for title, value in cards
    )
    charts_html = "\n".join(
        f"""
        <section class="chart-panel">
            <iframe src="charts/{filename}" loading="lazy"></iframe>
        </section>
        """
        for filename in chart_files
    )
    html = f"""<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Dashboard - Saude mental em tecnologia</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f6f7f4;
      --panel: #ffffff;
      --text: #263238;
      --muted: #60717a;
      --line: #d8ded8;
      --accent: #2f6f73;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: Arial, sans-serif;
    }}
    header {{
      padding: 28px 32px 18px;
      border-bottom: 1px solid var(--line);
      background: #ffffff;
    }}
    h1 {{
      margin: 0 0 8px;
      font-size: 28px;
      font-weight: 700;
      letter-spacing: 0;
    }}
    p {{
      margin: 0;
      color: var(--muted);
      line-height: 1.5;
    }}
    main {{
      width: min(1440px, 100%);
      margin: 0 auto;
      padding: 24px;
    }}
    .kpi-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 14px;
      margin-bottom: 22px;
    }}
    .kpi-card {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 16px;
      min-height: 92px;
    }}
    .kpi-card span {{
      display: block;
      color: var(--muted);
      font-size: 13px;
      margin-bottom: 10px;
    }}
    .kpi-card strong {{
      display: block;
      font-size: 26px;
      line-height: 1.1;
      color: var(--accent);
    }}
    .chart-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(520px, 1fr));
      gap: 18px;
    }}
    .chart-panel {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      min-height: 520px;
      overflow: hidden;
    }}
    iframe {{
      width: 100%;
      height: 520px;
      border: 0;
      display: block;
    }}
    @media (max-width: 720px) {{
      header {{ padding: 22px 18px 14px; }}
      main {{ padding: 16px; }}
      .chart-grid {{ grid-template-columns: 1fr; }}
      .chart-panel {{ min-height: 460px; }}
      iframe {{ height: 460px; }}
    }}
  </style>
</head>
<body>
  <header>
    <h1>Saude mental em tecnologia - Dashboard analitico</h1>
    <p>Indicadores visuais gerados a partir da tabela tratada no PostgreSQL.</p>
  </header>
  <main>
    <section class="kpi-grid">
      {cards_html}
    </section>
    <section class="chart-grid">
      {charts_html}
    </section>
  </main>
</body>
</html>
"""
    path = DASHBOARD_DIR / "dashboard.html"
    path.write_text(html, encoding="utf-8")
    print(f"Dashboard gerado: {path.relative_to(PROJECT_ROOT)}")


def main() -> None:
    wait_for_database()
    ensure_statistics_outputs()
    prepare_directories()

    create_burnout_distribution_chart()
    create_stress_histogram_chart()
    create_burnout_by_work_mode_boxplot()
    create_stress_burnout_scatter_chart()
    create_correlation_heatmap_chart()
    create_grouped_kpi_chart()
    create_dashboard_index()

    print("\nDashboard visual exportado com sucesso.")


if __name__ == "__main__":
    main()
