# Generated by Django 5.2.15 on 2026-06-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('chunked', 'Segmentado'), ('indexed', 'Indexado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=20),
        ),
    ]
